# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PF2e RPG Numbers & More
description: >- # this means to ignore newlines until "baseurl:"
    Home Place for Pf2e RPG Numbers Wiki
baseurl: "/pf2e-rpg-numbers/" # the subpath of your site, e.g. /blog
url: "https://chasarooniz.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: chasarooniZ

# Build settings
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
plugins:
    - jekyll-feed
auto_page_title: true
search_enabled: true
sidebar:
    - about
    - label: Critical
      children:
        - critical
    - label: Rolls
      children:
        - damage-numbers
        - check-and-attack-numbers
    - label: Token
      children:
        - burst-burrow
        - rotate-on-attack
        - shake-on-attack
        - shake-on-damaged
        - target-dodges
        - token-damage-shake
    - label: Text
      children:
        - finishing-moves
        - from-software-noun-verb
        - from-software-you-died
    - api

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
