on:
  release:
    types: [released]

jobs:

  update-changelog:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Update Changelog
      run: |
        RELEASE_TITLE=${{ github.event.release.name }}
        RELEASE_BODY=${{ github.event.release.body }}
        IS_PRERELEASE=${{ github.event.release.prerelease }}
        
        if [[ $IS_PRERELEASE == "false" ]]; then
          echo "## $RELEASE_TITLE" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "$RELEASE_BODY" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
        fi   
    - name: Commit Changelog
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'github-actions@example.com'
        git add CHANGELOG.md
        git commit -m "Update Changelog for ${{ github.event.release.tag_name }}"
        git push
